[build]
  command = "node index.js"  # Run your Node.js server
  publish = "."  # Set the root directory as the deployment folder

[dev]
  command = "node index.js"  # Run locally for testing
  port = 8888  # Default Netlify Dev port (change if needed)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
